# Generated by Django 3.1.1 on 2023-11-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamComment',
            new_name='Comment',
        ),
    ]
