# Generated by Django 3.1.1 on 2023-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20231123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=225),
            preserve_default=False,
        ),
    ]
