# Generated by Django 3.1.1 on 2023-11-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20231123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.major'),
        ),
    ]
