# Generated by Django 3.1.1 on 2023-11-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20231123_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
